GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlYkB0ZXN0LmZyIiwidXNlcklkIjoiNWVjZmYzNmZiMTVhNmJjM2UxMGIwYmQ2IiwiaWF0IjoxNTkxMTg5MTc2LCJleHAiOjE1OTExODkyMTZ9.RY5Lej6GhyeQdYUrUxJED71cR3L0JjJBSnMgVgFdZQY

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "firstname": "Sébastien",
  "lastname": "SEPTIER",
  "email": "seb@test.fr",
  "password": "test"
}

###

DELETE http://localhost:3000/api/users/5ecfe9b483e175f0a91c1d7a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlYkB0ZXN0LmZyIiwidXNlcklkIjoiNWVjZmYzNmZiMTVhNmJjM2UxMGIwYmQ2IiwiaWF0IjoxNTkxMTg5MjcxLCJleHAiOjE1OTExODkzMTF9.p_Krr8f6I6Lm_3T_fu-KJ4AGZ0jSGlTMcdO6T5PkrbM

###

PATCH http://localhost:3000/users/5e07cdb24816982bd0afcdd6
Content-Type: application/json

{
  "lastname": "SEPTIER"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "seb@test.fr",
  "password": "test"
}

###

POST http://localhost:4000/signup
Content-Type: application/json

{
  "firstname": "test",
  "lastname": "test",
  "email": "test@test.fr",
  "password": "test",
  "birthDate": ""
}