GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlYkB0ZXN0LmZyIiwidXNlcklkIjoiNWUwN2U1NDc3MmIzMjUzNGEwYTllODY4IiwiaWF0IjoxNTc3NjM4MDEyLCJleHAiOjE1Nzc2MzgwMzJ9.sfLL3T9VCJ4bqT-qerIqBzyuYyXHYpvAPs9oOa74vVw

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "firstname": "Sébastien",
  "lastname": "SEPTIER",
  "email": "seb@test.fr",
  "password": "test"
}

###

DELETE http://localhost:3000/users/5e07e4b072b32534a0a9e864

###

PATCH http://localhost:3000/users/5e07cdb24816982bd0afcdd6
Content-Type: application/json

{
  "lastname": "SEPTIER"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "seb@test.fr",
  "password": "test"
}

###

POST http://localhost:4000/signup
Content-Type: application/json

{
  "firstname": "Sébastien",
  "lastname": "SEPTIER",
  "email": "seb@test.fr",
  "password": "test"
}