GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlYkB0ZXN0LmZyIiwidXNlcklkIjoiNWUwN2U1NDc3MmIzMjUzNGEwYTllODY4IiwiaWF0IjoxNTc3NTc3MTUzLCJleHAiOjE1Nzc1NzcxNzN9.y5tKL73ntayxhB-Dm2AtKuGkdYVAKdWQ6KNxH_oUnxk

###

POST http://localhost:3000/users
Content-Type: application/json

{
  "firstname": "Sébastien",
  "lastname": "SEPTIER",
  "email": "seb@test.fr",
  "password": "test"
}

###

DELETE http://localhost:3000/users/5e07e4b072b32534a0a9e864

###

PATCH http://localhost:3000/users/5e07cdb24816982bd0afcdd6
Content-Type: application/json

{
  "lastname": "SEPTIER"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNlYkB0ZXN0LmZyIiwidXNlcklkIjoiNWUwN2U1NDc3MmIzMjUzNGEwYTllODY4IiwiaWF0IjoxNTc3NTc2MTQ5LCJleHAiOjE1Nzc1NzYxNjl9.YT9JKlN-1yhpqR-o419ctoQN-00ygxpfe2EU4qd5OOg

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "email": "seb@test.fr",
  "password": "test"
}

###

POST http://localhost:4000/signup
Content-Type: application/json

{
  "firstname": "Sébastien",
  "lastname": "SEPTIER",
  "email": "seb@test.fr",
  "password": "test"
}